apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-external-service
  namespace: argocd-operators
spec:
  # Use LoadBalancer for external cloud-managed access
  type: LoadBalancer 
  ports:
    - name: http
      # The external Load Balancer listens on port 80
      port: 80 
      protocol: TCP
      # Traffic is forwarded to the Pod's port 8080
      targetPort: 8080 
  selector:
    app: spring-boot-app
