apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  labels: # <-- MUST be indented EXACTLY here
    app: spring-boot-app
spec:
  selector:
    app: spring-boot-app # <-- MUST be indented EXACTLY here under 'spec'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
